### ISSUE TITLE
Address initialization regression

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Core#149]
```
Would you like to initialise .env.current to example values? (Y/N)
> Y
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    init_env('../.env.current')
  File "/Users/uqhkhosr/Dropbox/GitHub/RiPPLE-Core/server/src/ripple/load_env.py", line 26, in init_env
    user_answer = input("> ")
  File "<string>", line 1, in <module>
NameError: name 'Y' is not defined
```

**Comment by CaptainAchilles** [comment]
Work performed as part of #138
